name: Update Readme2

on:
  schedule:
    - cron: "0 * * * *"       # Corre cada hora
  workflow_dispatch:          # Permite ejecutarlo manualmente desde la pestaña Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Actualizar sección de actividad
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        with:
          COMMIT_MSG: "chore: actualizar actividad reciente"
          MAX_LINES: 10
