name: Update Readme

on:
  schedule:
    - cron: '0 */12 * * *' # Ejecutar cada 12 horas
  workflow_dispatch: # Permitir ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnan/blog-post-workflow@master
        with:
          # Aquí puedes configurar las variables de entorno si son necesarias
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
